/**
	Hold the current player and actor state of the server.

	lid == login id. Unique Hw or Login Id generated by client
	sid == user session id (determined by server in current session)
	socket == socket.io socket reference
	aid == actor id as determined by owner (sid-aid is unique identifier)
*/

const storage = ()=>{


	let idCounter = 0;

	//socket.io clients
	let clients = [];

	//login id (lid) => uid
	let loginSessionMap = {};

	//sid => socket
	let sessionSocketMap = {};
	let socketSessionMap = {};

	//sid => startup data
	let sessionPlayerMap = {};
	let sessionLoginMap = {};

	//sid-aid => startup data
	let actorMap = {};

	function resetAllData(){
		//array of socket.id
		clients = [];

		//maps
		loginSessionMap = {};
		sessionSocketMap = {};
		socketSessionMap = {};
		sessionPlayerMap = {};
		sessionLoginMap = {};
		actorMap = {};

		idCounter = 0;
	}

	function requestNewSessionId(){
		const newId = idCounter;
		idCounter++;
		return newId;
	}

	function onNewPlayer(playerStartupData, socket){
		//get a new session id
		let sid = requestNewSessionId();
		playerStartupData.sessionId = sid;

		//map our login id to session id. NB: two users on same computers will clash here
		loginSessionMap[playerStartupData.loginId] = sid;

		//store sid<->session maps
		sessionSocketMap[sid] = socket;
		socketSessionMap[socket.id] = sid;
		sessionLoginMap[sid] = playerStartupData.loginId;

		//have a way to lookup player startup data

		//remove loginData, should only be visible to server via
		//sessionLoginMap
		delete playerStartupData.loginId;	
		sessionPlayerMap[sid] = playerStartupData;

		return sid;
	}

	function sessionForSocket(socket){
		return socketSessionMap[socket.id];
	}

	function playerForSession(sid){
		return sessionPlayerMap[sid];
	}

	function onConnection(socket){
		clients.push(socket.id);
		const clientConnectedMsg = 'User connected ' + util.inspect(socket.id) + ', total: ' + clients.length;
		console.log(clientConnectedMsg);
		return clientConnectedMsg;
	}
	function deletePlayer(sid){
		delete sessionPlayerMap[sid];
		const playerSocket = sessionSocketMap[sid];
		delete sessionSocketMap[sid];
		const lid = sessionLoginMap[sid];
		delete sessionLoginMap[sid];
		delete loginSessionMap[lid];

		if(playerSocket){
			delete socketUserMap[playerSocket.id];
		}
	}
	function onDisconnect(socket){
		//remove player information
		const sid = sessionForSocket(socket);
		deletePlayer(sid);

		clients.pop(socket.id);
		const clientDisconnectedMsg = 'User disconnected ' + util.inspect(socket.id) + ', total: ' + clients.length;
		console.log(clientDisconnectedMsg);

		return clientDisconnectedMsg;
	}

	return {
		requestNewUserId,
		resetAllData,
		onNewPlayer,
		sessionForSocket,
		playerForSession,
		onConnection,
		deletePlayer,
		onDisconnect
	}
}

//this will fill exports
exports.resetData();

exports.storage = storage();